sudo: required

language: cpp

dist: bionic

group: edge

matrix:
  include:
    # VM-based 64-bit build (Clang)
    - os: linux
      dist: bionic
      sudo: required
      compiler: clang
      env:
      - DISTRIBUTION=ubuntu/bionic
      - DEPLOY_PACKAGE=false
      - DEPLOY_IMAGE=false
      - GENERIC_BUILD=false
      #- DEBUG_BUILD=true
      script:
      - bash ./CI/runci.sh ubuntu-18.04
      if: branch = master OR tag IS present
    - arch: arm64
      os: linux
      dist: bionic
      sudo: required
      compiler: clang
      env:
      - DISTRIBUTION=ubuntu/bionic
      - DEPLOY_PACKAGE=false
      - DEPLOY_IMAGE=false
      - GENERIC_BUILD=false
      #- DEBUG_BUILD=true
      script:
      - bash ./CI/runci.sh ubuntu-18.04
      if: branch = master OR tag IS present
env:
  global:
  - secure: DHaTv1euwlpVgePMbw0LEBihzru8VP5RmY7/TUdEpS1dBlJx6nyT6lgmyRcdb19RmTBUXZl1hm7Zu8TfqJJgfty4o9EnpLfTHbY7JwglSqbOo7b/FNAa1Qi0RhVDwc/WvFJDYBUvOtPtVQbPtVtECXm8PZcRqfOuEjkbHmmnIk8=

# Ship Akumuli logs to the S3 bucket
addons:
  artifacts:
    provider: s3
    s3_region: us-west-2
    access_key_id: "$ARTIFACTS_KEY"
    secret_access_key: "$ARTIFACTS_SECRET"
    bucket: "$ARTIFACTS_BUCKET"
    acl: public_read
    paths:
    - "${TRAVIS_BUILD_DIR}/akumuli.log"

# Packagecloud deployment configuration
deploy:
  provider: packagecloud
  repository: Akumuli
  username: Lazin
  dist: $DISTRIBUTION
  package_glob: "${TRAVIS_BUILD_DIR}/build/*.{deb,rpm}"
  token:
    secure: TNIqxlIMy4PUJIn65Yl7dyr1A+TVCMSCOUZOd/XlqlmjntFbxdBKY2M+bX5Cc+uOvNNxFU0m0/RpxYibeN8Juo3BTV0B8YJ4Hjr60F+Sag0UFvvDmxd4vzK+rm+XbYyyx0ukO2ETUxEqxaJaEi0CJPEvEiIeXyJAzIytoVNukkM=
  on:
    tags: true
    condition: $DEPLOY_PACKAGE = "true"
  skip_cleanup: true

after_success:
# Push docker image. Docker image should be created and the variables REPO,
# VERSION, and TAG should exist.
- if [[ $TRAVIS_PULL_REQUEST == "false" && $DEPLOY_IMAGE == "true" ]]; then
      echo "Pushing to $REPO $VERSION $TAG";
      sudo docker login -u "$DOCKER_USER" -p "$DOCKER_PASS";
      sudo docker push $REPO:$VERSION-$TAG;
  fi 
after_failure: 
- echo "Build failed"
